### PR TITLE
added code of conduct

### PR DESCRIPTION
**Pull request by pragyaasapkota**
The issue - [Adding Code of conducts](https://github.com/Asilshah006/--Hacktoberfest_2022/issues/260) is worked on this PR.

### CODE REVIEW

**Comment by pragyaasapkota** [comment]
@Asilshah006 
Please review this

**Comment by pragyaasapkota** [comment]
#26 
#27 
#28 
All three issues have been taken care of with this PR.

**Review by Asilshah006 — COMMENTED** [review]
I think this is Perfect

**Comment by pragyaasapkota** [comment]
Thank you!!!

**Pull request merged**
